import page from "../src/app/page";

export const GET_LANG_vi = () => {
    let array ={
      header:{
        language: 'Ngôn Ngữ',
        Home_Page: 'TRANG CHỦ',
        diary: 'NHẬT KÝ',
        Visa: 'VISA',
        Tour: "TOUR",
        Flashpacking: 'FLASHPACKING',
        voucher_combo: 'VOUCHER-COMBO',
        tickets_plane: 'VÉ MÁY BAY',
        news: 'TIN TỨC',
        review: 'REVIEW',
        All: 'Tất cả',
        Golf:'Golf',
        Golf_Course:'Sân golf',
        Golf_Package:'Gói golf',
        Tour_Travel:'Tour du lịch',
        // Tour:'Tour',
        Lodging:'Lưu trú',
        Hotel:'Khách sạn',
        Move:'Di chuyển',
        Plane:'Máy bay',
        Car:'Ô tô',
        Tour_Guide:'Hướng dẫn viên',
        Restaurant:'Nhà hàng',
        Spa:'Spa',
        Blog:'Blog',
        Company_Introduction:'Về chúng tôi',
        Contact:'Liên hệ',
        Gift_Certificate:'Phiếu quà tặng',
        Cart:'Giỏ hàng',
        View_Cart:'Xem giỏ hàng',
        Download_App:'Tải ứng dụng',
        Support:'Trợ giúp',
        Register:'Đăng ký',
        Log_In:'Đăng nhập',
        Search_Destinations:'Tìm theo điểm đến, hoạt động',
        Search:'Tìm kiếm',
        Total_Money:'Tổng tiền',
        Items:'items',
        Information:'Thông tin',
        Log_Out:'Đăng xuất',
        Other:'Khác',
        Recently_Viewed:'Xem gần đây',
        Adult:'Người lớn',
        Area:'Khu vực',
        Holes:'Số hố',
        Type:'Loại',
        P2r1:'2 người 1 phòng',
        P1r1:'1 người 1 phòng',
        Children:'Trẻ em',
        Tourism: 'Du lịch',
        Transport: 'Vận chuyển',
        Promotion: 'Khuyến mãi',
      },
      main:{
        Search_Destinations:'Tìm theo điểm đến, hoạt động',
        Search:'Tìm kiếm',
        Cheap_Flights:'Chuyến bay giá tốt',
        Favorite_Tour:'Tour du lịch yêu thích',
        Tour:'Tour',
        Private_Tour:'Tour Riêng',
        Compound_Tour:'Tour Ghép',
        Car_Tour:'Tour Xe',
        Tour_Price:'Giá tour',
        People:'Người',
        View_All:'Xem tất cả',
        Favorite_Golf:'Golf yêu thích',
        Golf_Course:'Sân golf',
        Golf_Price:'Giá golf',
        Golf_Car:'Xe điện',
        Included:'Bao gồm',
        News_Balotour:'Hoạt động tin tức của Nhanhtravel',
        Fascinating_Experience:'Trải nghiệm hấp dẫn cho mọi người',
        Dowload_Now:'TẢI ỨNG DỤNG BALOTOUR',
        First_Order:'NHẬN NGAY 10% ƯU ĐÃI CHO ĐƠN HÀNG ĐẦU TIÊN',
        Booking_Tourism:'Đặt các dịch vụ du lịch nhanh chóng tiện lợi.',
        The_Best_Prices:'Luôn có giá tốt nhất và nhiều chương trình khuyến mãi hấp dẫn và tích lũy điểm.',
        Intuitive_Application:'Giao diện ứng dụng trực quan dễ dàng tham khảo thông tin sản phẩm, dịch vụ.' ,
        Online_Payment:'Thanh toán trục tuyến dễ dàng với nhiều hình thức thanh toán đa dạng.',
        The_Team_Of_Counselor:'Đội ngũ nhân viên tư vấn nhiều kinh nghiệm, chăm sóc tận tình.',
        Business_Partner:'Đối tác',
        Favorite_Golf_Package:'Gói golf yêu thích',
        Golf_Package:'Gói golf',
        Golf_Package_Price:'Giá gói',
        Slogan1:'Điểm đến thú vị, vui chơi thỏa thích',
        Slogan2:'Trải nghiệm mới làm tăng hoocmon hạnh phúc của bạn',
      },
      footer:{
        Address_Content:'1.07 và 1.08, Tầng Trệt + Lửng, Tòa nhà Ruby Garden, 2A Nguyễn Sỹ Sách, Phường 15, Quận Tân Bình, Thành phố Hồ Chí Minh, Việt Nam',
        The_Main_Commercial_Aspect:'Lĩnh vực kinh doanh chính: Lữ hành quốc tế - Tổ chức sự kiện - Golf - Tổ chức giải đấu Golf - Booking các dịch vụ liên quan đến du lịch trong và ngoài nước',
        Business_Partner:'Đối tác',
        Company_Introduction:'Về chúng tôi',
        Supplier_Registration:'Đăng ký nhà cung cấp',
        Partner_Login:'Đối tác đăng nhập',
        Affiliate_Partner:'Đối tác liên kết',
        Celebrity_Show:'Chương trình người nổi tiếng',
        Agent_Program:'Chương trình cho đại lý',
        Affiliate_Distribution:'Hợp tác Marketing và phân phối',
        Term_Use :'Điều khoản sử dụng',
        Privacy_Policy:'Chính sách bảo mật',
        Cookie_Policy:'Chính sách cookie',
        Regulatory_Policy:'Chính sách quy định',
        Download_Here:'Tải ứng dụng tại đây',
        Connecting_Us:'Kết nối với chúng tôi',
        Enthusiasm:'Nhiệt Huyết',
        Creative:'Sáng Tạo',
        Responsibility:'Trách Nhiệm',
        Honest:'Trung Thực',

      },
      golf:{
        Golf_Service :'Dịch vụ golf',
        Filter :'Bộ lọc',
        Search_Keywords:'Từ khóa tìm kiếm',
        Golf_Course:'Sân golf',
        Golf_Price:'Giá golf',
        Golf_Car:'Xe điện',
        Included:'Bao gồm',
        Not_Included:'Không bao gồm',
        Image:'Hình ảnh',
        Introduction:'Giới thiệu',
        Policy_Regulations:'Quy định chính sách',
        Scorecard:'Thông số',
        Maps:'Bản đồ',
        Clear:'Xóa lọc',
        Teetime:'Thời gian chơi',
        Session:'Buổi chơi',
        Holes:'Số hố',
        Hour:'Giờ',
        Number_Of_Guests:'Số khách',
        Booking:'Đặt ngay',
        Cancel:'Hủy',
        Chosen:'Đã được chọn',
        Being_Selected:'Đang được chọn',
        Time_Out:'Hết giờ rồi. Vui lòng chọn thời gian khác',
        People:'Người'
      },
      golf_package:{
        Golf_Package_Service :'Dịch vụ gói golf',
        Filter :'Bộ lọc',
        Search_Keywords:'Từ khóa tìm kiếm',
        Golf_Package:'Gói golf',
        Golf_Package_Price:'Giá gói',
        People:'Người',
        Cancellation:'Hoàn huỷ miễn phí trong 24h',
        Present_Voucher:'Xuất trình voucher điện tử',
        Language_tour:'Ngôn ngữ: Theo chương trình tour',
        Pick_Up_Point_Tour:'Tuỳ chọn đón tại khách sạn',
        Day_Ticket:'Vé theo ngày cố định',
        Time:'Thời gian',
        Hotel:'Khách sạn',
        Number_People:'Số người tối thiểu - tối đa',
        Introduction:'Giới thiệu',
        Schedule:'Lịch trình',
        Policy:'Chính sách',
        Payment_Policy:'Chính sách thanh toán',
        Cancellation_Policy:'Chính sách hủy',
        Detail_Tour : 'Chi tiết gói đã chọn',
        Instant_Confirmation:'Xác nhận tức thời',
        General_Terms:'Điều khoản chung',
        Confirm:'Xác nhận',
        Confirm_1:'- Xác nhận ngay tức thời. Nếu bạn không nhận được email xác nhận đơn hàng, hãy liên hệ với chúng tôi',
        User_Manual:'Hướng dẫn sử dụng',
        Expiry_Date:'Thời hạn sử dụng',
        Voucher_1 : '- Voucher chỉ có giá trị trong ngày giờ được chỉ định',
        Voucher_2 : '- Sử dụng voucher vào ngày giờ đã định',
        Hour_Open :'Giờ hoạt động',
        Week_Time : '- Thứ Hai-Chủ Nhật: 08:30-18:00',
        Detail_Voucher:'Mô tả các loại voucher',
        Voucher_3 : '- Xuất trình voucher in sẵn hoặc voucher trên điện thoại',
        View_All:'Xem tất cả',
        Select_Service:'Vui lòng chọn ngày & gói dịch vụ' ,
        Choose_Tour_Date:'Xin chọn ngày đi tour',
        Choose_Time:'Xin chọn loại thời gian',
        Choose_Type_room:'Xin chọn loại phòng',
        Quantity:'Số lượng',
        Children:'Trẻ em',
        Adult:'Người lớn',
        P2r1:'2 người 1 phòng',
        P1r1:'1 người 1 phòng',
        People:'Người',
        Hotel:'Khách sạn',
        Time:'Thời gian',
        Departure_Day:'Ngày khởi hành',
        Return_Day:'Ngày trở về',
        Pick_Up_Time:'Thời gian đón',
        Program_Service:'Phục vụ theo chương trình',
        Type_Of_Room:'Loại phòng',
        Tour_Guide:'Hướng dẫn viên',
        All_People:'Tổng số người',
        Tax:'Thuế',
        Tax_Text:'Đã bao gồm 10% VAT',
        Total_Payment:'Tổng tiền thanh toán',
        Add_Cart:'Thêm vào giỏ hàng',
        Day:'Ngày'
      },
      tour:{
        Tour_Service :'Dịch vụ tour',
        Filter :'Bộ lọc',
        Search_Keywords:'Từ khóa tìm kiếm',
        Tour:'Tour',
        Private_Tour:'Tour Riêng',
        Compound_Tour:'Tour Ghép',
        Car_Tour:'Tour Xe',
        Tour_Price:'Giá tour',
        People:'Người',
        Car:'Xe',
        Cancellation:'Hoàn huỷ miễn phí trong 24h',
        Present_Voucher:'Xuất trình voucher điện tử',
        Language_tour:'Ngôn ngữ: Theo chương trình tour',
        Pick_Up_Point_Tour:'Tuỳ chọn đón tại khách sạn',
        Day_Ticket:'Vé theo ngày cố định',
        Time:'Thời gian',
        Type_Tour:'Loại tour',
        Number_People:'Số người tối thiểu - tối đa',
        People:'Người',
        Introduction:'Giới thiệu',
        Schedule:'Lịch trình',
        Include:'Bao gồm',
        Not_Include:'Không bao gồm',
        Policy:'Chính sách',
        Note:'Lưu ý',
        Day:'Ngày',
        Payment_Policy:'Chính sách thanh toán',
        Cancellation_Policy:'Chính sách hủy',
        Child_Policy:'Chính sách trẻ em',
        Detail_Tour : 'Chi tiết gói đã chọn',
        Tour_Price:'Giá tour',
        Instant_Confirmation:'Xác nhận tức thời',
        General_Terms:'Điều khoản chung',
        Confirm:'Xác nhận',
        Confirm_1:'- Xác nhận ngay tức thời. Nếu bạn không nhận được email xác nhận đơn hàng, hãy liên hệ với chúng tôi',
        User_Manual:'Hướng dẫn sử dụng',
        Expiry_Date:'Thời hạn sử dụng',
        Voucher_1 : '- Voucher chỉ có giá trị trong ngày giờ được chỉ định',
        Voucher_2 : '- Sử dụng voucher vào ngày giờ đã định',
        Hour_Open :'Giờ hoạt động',
        Week_Time : '- Thứ Hai-Chủ Nhật: 08:30-18:00',
        Detail_Voucher:'Mô tả các loại voucher',
        Voucher_3 : '- Xuất trình voucher in sẵn hoặc voucher trên điện thoại',
        View_All:'Xem tất cả',
        Product_Information:'Thông tin sản phẩm',
        Select_Service:'Vui lòng chọn ngày & gói dịch vụ' ,
        Choose_Tour_Date:'Xin chọn ngày đi tour',
        Choose_Time:'Xin chọn loại thời gian',
        Quantity:'Số lượng',
        Children:'Trẻ em',
        Adult:'Người lớn',
        People:'Người',
        Time:'Thời gian',
        Departure_Day:'Ngày khởi hành',
        Return_Day:'Ngày trở về',
        Pick_Up_Time:'Thời gian đón',
        Program_Service:'Phục vụ theo chương trình',

        Tour_Guide:'Hướng dẫn viên',
        All_People:'Tổng số người',
        Tax:'Thuế',
        Tax_Text:'Đã bao gồm 10% VAT',
        Total_Payment:'Tổng tiền thanh toán',
        Add_Cart:'Thêm vào giỏ hàng',
        Toast_Max_Adult:'Số người tối đa đã đủ',
        Toast_Min_Adult:'Số người tối thiểu đã đủ',
        Toast_Max_Children:'Số trẻ em tối đa đã đủ',
        Toast_Min_Children:'Số trẻ em tối thiểu đã đủ',
        Add_Cart:'Thêm giỏ hàng thành công',
        Not_Account:'Chưa đăng nhập tài khoản'
      },
      hotel:{
        Hotel:'Khách sạn',
        Want_Go:'Bạn muốn đi đâu?',
        Check_In:'Ngày nhận phòng',
        Check_Out:'Ngày trả phòng',
        Booking_Information:'Thông tin đặt phòng',
        Adult:'Người lớn',
        Children:'Trẻ em',
        Log_In_To_Receive:'Đăng nhập để nhận thêm ưu đãi 15% khi đặt phòng khách sạn, vé máy bay',
        Number_Of_Room:'Số phòng',
        Log_In:'Đăng nhập',
        Hotel_Services:'Dịch vụ khách sạn',
        Filter:'Bộ lọc',
        All: 'Tất cả',
        Start_1:'Khách sạn 1 sao',
        Start_2:'Khách sạn 2 sao',
        Start_3:'Khách sạn 3 sao',
        Start_4:'Khách sạn 4 sao',
        Start_5:'Khách sạn 5 sao',
        Room_Prices:'Giá phòng',
        People:'Người',
        // Cancellation:'Hoàn huỷ miễn phí trong 24h',
        Present_Voucher:'Xuất trình voucher điện tử',
        Language_tour:'Ngôn ngữ: Theo chương trình tour',
        Pick_Up_Point_Tour:'Tuỳ chọn đón tại khách sạn',
        Day_Ticket:'Vé theo ngày cố định',
        Time_Check:'Thời gian nhận và trả phòng',
        Address:'Địa chỉ',
        Number_People:'Số người tối thiểu - tối đa',
        Number_People_Text:'tùy theo số khách của mỗi phòng',
        Information:'Thông tin',
        Introduction:'Giới thiệu',
        Policy:'Chính sách',
        Regulations:'Quy định',
        Maps:'Bản đồ',
        Service_Packages:'Các gói dịch vụ',
        Image:'Hình ảnh',
        View_room:'Chi tiết phòng',
        About_Room:'Về phòng này',
        Type_Of_Room:'Loại phòng',
        Room_Size:'Diện tích phòng',
        Max_Adult:'Số người lớn tối đa',
        Max_Children:'Số trẻ em tối đa',
        Number_Beds:'Số Giường',
        Type_Beds:'Loại Giường',
        Have_Window:'Có cửa sổ',
        Have_Not_Window:'Không có cửa sổ',
        Have_Xtra_Bed:'Có giường phụ',
        Have_Not_Xtra_Bed:'Không có giường phụ',
        Utilities:'Tiện ích',
        Beds:'Giường',
        Empty_room:'Phòng trống',
        Night:'đêm',
        Booking:'Đặt ngay',
        Last_Price:'Giá cuối cùng',
        Not_Breakfast :'Không gồm bữa sáng',
        Cancellation:'Hủy phòng theo chính sách',
        Free_Wifi:'WiFi miễn phí',
        View_Cancellation_Policy:'Xem Chính sách huỷ phòng',
        View_Cancellation_Policy_Text_1 : 'Hủy phòng không thu phí nếu huỷ đặt chỗ này.',
        View_Cancellation_Policy_Text_2 : 'Không thể thay đổi số đêm nghỉ và loại phòng.',
        View_Cancellation_Policy_Text_3 : 'Thời gian hiển thị là giờ địa phương.',
        Apply_Pay_Check_In : 'Áp dụng Thanh toán khi nhận phòng',
        Apply_Pay_Check_In_1 : 'Tiết kiệm cho đến khi nhận phòng!',
        Apply_Pay_Check_In_Text_1:'Áp dụng Thanh toán khi nhận phòng',
        Apply_Pay_Check_In_Text_2:'Cho chuyến đi thêm linh hoạt: KHÔNG CẦN THANH TOÁN NGAY khi đặt phòng! Bạn có đặt ngay phòng có giá tốt nhất hôm nay và thanh toán sau bằng tiền mặt hoặc thẻ khi nhận phòng.',
        Extra_Bed_More:'Thêm giường phụ phòng',
        Company_Fee:'Phí công ty',
        Total_Money:'Tổng tiền',
      },
      cart:{
        Cart:'Giỏ hàng',
        Golf_Services:'Dịch vụ golf',
        Tour_Services:'Dịch vụ tour',
        Golf_Package_Service :'Dịch vụ gói golf',
        Hotel_Services:'Dịch vụ khách sạn',
        Area:'Khu vực',
        Holes:'Hố',
        Adult:'Người lớn',
        Children:'Trẻ em',
        Time:'Thời gian',
        Golf_day:'Ngày chơi golf',
        P2r1:'2 người 1 phòng',
        P1r1:'1 người 1 phòng',
        Go:'Đi',
        Back_Go :'Về',
        Room : 'Phòng',
        Extra_Bed:'Giường phụ',
        Check_In_Date_Hotel:'Ngày nhận phòng',
        Check_Out_Date_Hotel:'Ngày Trả phòng',
        Number_Of_Room:'Số phòng',
        Private_Tour:'Tour Riêng',
        Compound_Tour:'Tour Ghép',
        Car_Tour:'Tour Xe',
        Delete:'Xóa',
        Total:'Tổng cộng',
        Unit:'Đơn vị',
        Next:'Tiếp theo',
      },
      order_summary:{
        Golf_Services:'Dịch vụ golf',
        Tour_Services:'Dịch vụ tour',
        Golf_Package_Service :'Dịch vụ gói golf',
        Hotel_Services:'Dịch vụ khách sạn',
        Select_Order:'Chọn đơn hàng',
        Check_Information:'Kiểm tra thông tin',
        Pay:'Thanh toán',
        Area:'Khu vực',
        Holes:'Hố',
        Adult:'Người lớn',
        Children:'Trẻ em',
        Time:'Thời gian',
        Golf_day:'Ngày chơi golf',
        P2r1:'2 người 1 phòng',
        P1r1:'1 người 1 phòng',
        Go:'Đi',
        Back_Go :'Về',
        Room : 'Phòng',
        Extra_Bed:'Giường phụ',
        Number_Extra_Bed:'Số giường phụ',
        Check_In_Date_Hotel:'Ngày nhận phòng',
        Check_Out_Date_Hotel:'Ngày Trả phòng',
        Number_Of_Room:'Số phòng',
        Private_Tour:'Tour Riêng',
        Compound_Tour:'Tour Ghép',
        Car_Tour:'Tour Xe',
        Buyer_Information:'Thông tin người mua',
        Full_Name:"Họ và tên",
        Account_Name:'Tên tài khoản',
        Email:'Email',
        Phone:'Phone',
        Country:'Quốc gia:',
        Nationality:'Quốc Tịch',
        Edit:'Chỉnh sửa',
        Communications:'Thông tin liên lạc',
        Contact_Method:'Phương thức liên lạc',
        Contact_number:'Số liên lạc',
        Pick_Up_Address:'Địa chỉ đón',
        Paying_Address:'Địa chỉ trả ',
        Default:'Mặc định',
        Note_Address:'Lưu ý: Ghi rõ địa chỉ để Nhanhtravel có thể đón và trả bạn sớm nhất',
        Save:'lưu',
        Add_Contacts:'Thêm địa chỉ liên lạc',
        Request:'Yêu cầu',
        Order_Summary:'Tóm tắt đơn hàng',
        Total:'Tổng cộng',
        Include:'Bao gồm',
        Not_Included:'Không bao gồm',
        Delete:'Xóa',
        People:'Người',
        Type_Tour:'Loại tour',
        Type_Hotel:'Loại phòng khách sạn',
        Next:'Tiếp theo',
      },
      payment_method:{
        Select_Order:'Chọn đơn hàng',
        Check_Information:'Kiểm tra thông tin',
        Pay:'Thanh toán',
        Payment_methods:'Phương thức thanh toán',
        Payment_methods_1:'- Sử dụng tiền mặt hoặc phương thức chuyền khoản thông thường',
        Payment_methods_2:'- Sử dụng ví điện tử',
        Order_Summary:'Tóm tắt đơn hàng',
        Total:'Tổng cộng',
        Buyer_Information:'Thông tin người mua',
        Account_Name:'Tên tài khoản',
        Email:'Email',
        Phone:'Phone',
        Nationality:'Quốc Tịch',
        Communications:'Thông tin liên lạc',
        Contact_Method:'Phương thức liên lạc',
        Contact_number:'Số liên lạc',
        Pick_Up_Address:'Địa chỉ đón',
        Paying_Address:'Địa chỉ trả ',
        Request:'Yêu cầu',
        Pay_Now:'Thanh toán ngay',
      },
      order_view:{
        Text_Success:'Tuyệt vời! bạn đã đặt hàng thành công. Cảm ơn bạn đã chọn Nhanhtravel',
        Order:'Đơn hàng',
        See_Details:'Xem chi tiết',
        Code_Orders:'Mã đơn hàng',
        Order_Date:'Ngày đặt hàng',
        Payment_Methods:'Phương thức thanh toán',
        Payment_Status:'Tình trạng thanh toán',
        Transfer:'Chuyển khoản',
        Account_Name:'Tên tài khoản',
        Account_No:'Số tài khoản',
        At_The_Bank:'Tại ngân hàng',
        Or:'Hoặc',
        Note:'Để đảm bảo quyền lợi, khách hàng cần lưu ý',
        Note_1:'Yêu cầu quý khách chuyển đúng số tiền thì booking được xác nhận ngay.',
        Note_2:'Khi chuyển khoản, trong phần nội dung thanh toán, bạn vui lòng ghi rõ như sau',
        Note_3:'Đây là mã đơn hàng chứa các dịch vụ của bạn vừa đặt.',
        Note_4:'Nếu bạn ghi sai cú pháp này, Nhanhtravel hoàn toàn không chịu trách nhiệm trong trường hợp dịch vụ không được đăng kí hoặc gia hạn kịp thời.',
        Text:'Nhân viên Nhanhtravel sẽ liên hệ với bạn để xác nhận đơn hàng trong thời gian sớm nhất.',
        Text_1:'Dịch vụ chỉ được đăng kí / gia hạn khi nhận được thanh toán và thông tin chính xác, đầy đủ.',
        Text_2:'Đơn hàng đã được gởi về email: ',
        Text_3:'. Nếu không tìm thấy vui lòng kiểm tra tong hộp thư Spam hoặc Junk Folder.',
        Text_4:'Nếu bạn cần hỗ trợ, vui lòng gọi vào số Hotline: (+84) 903001205 hoặc 0909991205',
      },
      contact:{
        Our_Information:'Thông tin của chúng tôi',
        Our_Information_Text:'Hỗ trợ 24/7 với bất cứ lúc nào - bất kỳ nơi đâu',
        Hotline:'Hotline',
        Fanpage:'Fanpage',
        Email:'Email',
        Address:'Địa chỉ',
        Text:'Sẵn sàng để đồng hành?',
        Text_1:'Nhanhtravel là doanh nghiệp chuyên hoạt động trong các lĩnh vực dịch vụ du lịch trong và ngoài nước, tổ chức sự kiện, book khách sạn, sân golf, cho thuê xe, hướng dẫn viên, visa ... bằng uy tín và kinh nghiệm của mình, Nhanhtravel đã và đang hợp tác rất hiệu quả với nhiều doanh nghiệp trong và ngoài nước.',
        Text_2:'Với mong muốn mở rộng, phát triển kinh doanh và phát huy thế mạnh của mình Nhanhtravel không ngừng đổi mới nâng cao chất lượng nhằm mang đến sự hài lòng cho Quý khách.',
      },
      about:{
        About_Balotour:'Về Nhanhtravel',
        About_Balotour_Text:'Chuyên cung cấp giải pháp chuyển đổi số hàng đầu cho doanh nghiệp du lịch.',
        Text:'Nhiệm vụ của chúng tôi là hỗ trợ những nhà quản trị có thể điều hành doanh nghiệp du lịch chuyên nghiệp và đạt hiệu quả cao nhất. ',
        Text_1:'Thông qua hệ thống khép kín của Nhanh Travel, doanh nghiệp sẽ tối ưu được quy trình quản lý đơn hàng; điều hành tour; quản lý sản phẩm; quản lý lịch trình xe, tài xế, huấn luyện viên; quản lý nhà cung cấp; quản lý đại lý, cộng tác viên; giao việc và đề xuất; tài chính kế toán; quản lý nhân sự; hệ thống báo cáo; chăm sóc khách hàng. Qua đó nâng cao hiệu quả kinh doanh, đáp ứng được nhu cầu của khách hàng cũng như là bắt kịp xu hướng chuyển đổi số trên toàn thế giới.',
        Text_2:'Cùng với sự phát triển của cách mạng công nghệ 4.0, Nhanh Travel đã, đang và sẽ tiếp tục hoàn thiện và hỗ trợ các doanh nghiệp du lịch trong quá trình phát triển. ',
        Text_3:'Nhanh Travel – Giúp vận hành nhanh, tinh gọn, rõ ràng, rút ngắn thời gian vận hành của chủ doanh nghiệp lữ hành và sân Golf. Chúng tôi hy vọng mình có thể góp phần công sức nhỏ giúp phát triển ngành du lịch Việt Nam càng phát triển thịnh vượng.',
        Text_4 :' Kính chúc quý khách luôn có những chuyến tham quan du lịch & nghỉ dưỡng vui vẻ.',
        Vison_Misson_Titile:'TẦM NHÌN - SỨ MỆNH',
        Vison_Titile:'TẦM NHÌN',
        Vison_Titile_Text:'Nhanh Travel phấn đấu trở thành top 3 doanh nghiệp cung cấp giải pháp chuyển đổi số toàn diện cho ngành du lịch tại Việt Nam. Khẳng định vị thế trong ngành công nghệ chuyển đổi số tại Việt Nam và Quốc Tế. ',
        Misson_Titile:'SỨ MỆNH',
        Misson_Titile_Text:'Chúng tôi ước mơ, khao khát được đồng hành cùng doanh nghiệp du lịch Việt Nam trong quá trình chuyển đổi số. Thông qua hệ thống quản trị của Nhanh Travel, doanh nghiệp du lịch có thể phát triển mạnh mẽ và ổn định.',
        Core_Values_Title:'GIÁ TRỊ CỐT LÕI',
        Enthusiasm:'Nhiệt huyết',
        Enthusiasm_Text:'Nhiệt quyết là hơi thở, mục đích sống, là mục tiêu của bản thân và tập thể Nhanhtravel. Chúng tôi quyết chinh phục mọi thử thách bằng nhiệt huyết và niềm đam mê của mình.',
        Responsibility:'Trách Nhiệm',
        Responsibility_Text:'Nhanhtravel nhận thức rõ và có trách nhiệm đến cùng nhằm đảm bảo tính đúng đắn, chắc chắn với các cam kết, hoạt động của doanh nghiệp đối với chính mình, khách hàng, đối tác và xã hội.',
        Creative:'Sáng tạo',
        Creative_Text:'Sáng tạo là linh hồn là sức sống, chúng tôi đề cao tin thần dám nghĩ dám làm, không ngừng tìm kiếm giải pháp mang lại lợi ích vượt trội cho khách hàng và đối tác.',
        Honest:'Trung thực',
        Honest_Text:'Cam kết tôn trọng sự thật khách quan. Ngay thẳng, liêm chính, học hỏi từ sai lầm.',
        Company_Chart:"SƠ ĐỒ CÔNG TY",
        Partner:'ĐỐI TÁC',
        Client:'KHÁCH HÀNG',
      }

    }
    return array
  };

export const GET_LANG_ko = () => {
    let array ={
      header:{
        language: '언어',
        Home_Page: '홈페이지',
        diary: '다이어리',
        Visa: '비자',
        Flashpacking: '플래시패킹',
        voucher_combo: '바우처 콤보',
        tickets_plane: '항공권',
        review: '검토',
        news: '소식',
        All: '모두',
        Golf:'골프',
        Golf_Course:'골프장',
        Golf_Package:'골프 패키지',
        Tour_Travel:'관광 투어',
        Tour:'투어',
        Lodging:'숙소',
        Hotel:'호텔',
        Move:'운전',
        Plane:'비행기',
        Car:'렌트카',
        Tour_Guide:'가이드',
        Restaurant:'식당',
        Spa:'스파/마사지',
        Blog:'블로그',
        Company_Introduction:'회사 소개',
        Contact:'연락처',
        Gift_Certificate:'쿠폰',
        Cart:'자방구니',
        View_Cart:'자방구니 보기',
        Download_App:'앱 다운로드',
        Support:'서포트',
        Register:'등록',
        Log_In:'로그인',
        Search_Destinations:'어디로 떠나세요?',
        Search:'확인',
        Total_Money:'총금액',
        Items:'아이템',
        Information:'투어 정보',
        Log_Out:'로그 아웃',
        Other:'다른',
        Recently_Viewed:'최근에 본',
        Adult:'성인',
        Children:'아이',
        Area:'영역',
        Holes:'홀수',
        Type:'유형',
        P2r1:'2인1실',
        P1r1:'1인 1실',
        Instant_Confirmation:'즉시 확인',
        Tourism: '관광 여행',
        Transport : '수송',
        Promotion: '홍보',
      },
      main:{
        Search_Destinations:'어디로 떠나세요?',
        Search:'확인',
        Cheap_Flights:'가성비 항공편',
        Favorite_Tour:'유행한 관광투어',
        Tour:'투어',
        Private_Tour:'개인 투어',
        Compound_Tour:'컴파운드 투어',
        Car_Tour:'자동차 투어',
        Tour_Price:'투어 가격',
        People:'인',
        View_All:'다 보기',
        Favorite_Golf:'유행한 골프장',
        Golf_Course:'골프장',
        Golf_Price:'그린피',
        Golf_Car:'카트피',
        Included:'포함',
        News_Balotour:'발로투어의 뉴스',
        Fascinating_Experience:'여러분에게 재미있는 체험',
        Dowload_Now:'발로투어 앱 다운로드',
        First_Order:'처음 오다지 10% 할인',
        Booking_Tourism:'엡에서 빠르고 편하게 부킹',
        The_Best_Prices:'가장 좋은 가격 및 프로모션 제공',
        Intuitive_Application:'쉡게 발로투어의 상품 및 서비스 참고' ,
        Online_Payment:'다양한 결제 방법으로 단순히 온라인 결제',
        The_Team_Of_Counselor:'열정적이고 경험 많이 지니는 담당자들',
        Business_Partner:'상대방',
        Favorite_Golf_Package:'좋아하는 골프 패키지',
        Golf_Package:'골프 패키지',
        Golf_Package_Price:'패키지 가격',
        Slogan1:'흥미로운 목적지, 재미있게 보내세요',
        Slogan2:'새로운 경험은 행복 호르몬을 증가시킵니다',
      },
      footer:{
        Address_Content:'Ruby Garden Building, 2A Nguyen Sy Sach, Ward 15, District Tan Binh, Ho Chi Minh City, Vietnam',
        The_Main_Commercial_Aspect:'사업분야: 국제여행 영업 - 이벤트 조직 - 골프 - 골프 토너먼트 조직 - 국내외 여행 서비스 부킹',
        Business_Partner:'상대방',
        Company_Introduction:'회사 소개',
        Supplier_Registration:'제공자 등록',
        Partner_Login:'상대방 로그인',
        Affiliate_Partner:'상대방 연결',
        Celebrity_Show:'연예인 쇼',
        Agent_Program:'에이전트 프로그래밍',
        Affiliate_Distribution:'마켓팅 연결 및 분ㅂ',
        Term_Use :'이용약관',
        Privacy_Policy:'비밀유지 정책',
        Cookie_Policy:'쿠키 정책',
        Regulatory_Policy:'규제 정책',
        Download_Here:'여기로 앱 다운로드',
        Connecting_Us:'발로투어와 연락',
        Enthusiasm:'열광',
        Creative:'창의적인',
        Responsibility:'책임',
        Honest:'솔직한',
      },
      golf:{
        Golf_Service :'골프 서비스',
        Filter :'필터',
        Search_Keywords:'키워드 검색',
        Golf_Course:'골프장',
        Golf_Price:'그린피',
        Golf_Car:'카트피',
        Included:'포함',
        Not_Included:'포함되지',
        Image:'이미지',
        Introduction:'소개',
        Policy_Regulations:'규제 정책',
        Scorecard:'스코어카드',
        Maps:'위치정보',
        Clear:'적용 해제',
        Teetime:'티옵',
        Session:'세션',
        Holes:'홀수',
        Hour:'시간',
        Number_Of_Guests:'인원',
        Booking:'예약하기',
        Cancel:'취소',
        Chosen:'선택',
        Being_Selected:'선발 중',
        Time_Out:'때때로. 다른 시간을 선택하세요.',
        People:'인',
      },
      golf_package:{
        Golf_Package_Service :'골프 패키지 서비스',
        Filter :'필터',
        Search_Keywords:'키워드 검색',
        Golf_Package:'골프 패키지',
        Golf_Package_Price:'패키지 가격',
        People:'인',
        Cancellation:'24시간 이내 무료 취소',
        Present_Voucher:'전자 바우처 제시',
        Language_tour:'언어: 투어 프로그램에 따라',
        Pick_Up_Point_Tour:'옵션 호텔 픽업',
        Day_Ticket:'정기권',
        Time:'시간',
        Hotel:'호텔',
        Number_People:'최소 인원 - 최대',
        Introduction:'소개',
        Schedule:'일정',
        Policy:'정책',
        Payment_Policy:'지불 정책',
        Cancellation_Policy:'취소 정책',
        Detail_Tour : '선택한 패키지 세부 정보',
        Instant_Confirmation:'즉시 확인',
        General_Terms:'일반 조건',
        Confirm:'확인하다',
        Confirm_1:'- 즉시 확인. 주문 확인 이메일을 받지 못한 경우 당사에 문의하십시오.',
        User_Manual:'사용자 매뉴얼',
        Expiry_Date:'만료일',
        Voucher_1 : '- 바우처는 지정된 날짜와 시간에만 유효합니다.',
        Voucher_2 : '- 지정된 날짜와 시간에 바우처를 사용하세요.',
        Hour_Open :'영업시간',
        Week_Time : '- 월요일~일요일: 08:30~18:00',
        Detail_Voucher:'상품권 종류 설명',
        Voucher_3 : '- 출력된 바우처 또는 모바일 바우처 제시',
        View_All:'다 보기',
        Select_Service:'서비스 및 시간을 선택하세요' ,
        Choose_Tour_Date:'날짜',
        Choose_Time:'시간',
        Choose_Type_room:'객실 유형을 선택하세요.',
        Quantity:'인원',
        Children:'아이',
        Adult:'성인',
        P2r1:'2인1실',
        P1r1:'1인 1실',
        People:'인',
        Hotel:'호텔',
        Time:'시간',
        Departure_Day:'출발일자',
        Return_Day:'도착일자',
        Pick_Up_Time:'픽업 시간',
        Program_Service:'프로그램에 따라 서비스함',
        Type_Of_Room:'객실 종류',
        Tour_Guide:'가이드',
        All_People:'총인원',
        Tax:'세금',
        Tax_Text:'10% 세금 포함',
        Total_Payment:'총 지불금',
        Add_Cart:'자방구니에 넣기',
        Day:'낮'



      },
      tour:{
        Tour_Service :'투어 서비스',
        Filter :'필터',
        Search_Keywords:'키워드 검색',
        Tour:'투어',
        Private_Tour:'개인 투어',
        Compound_Tour:'컴파운드 투어',
        Car_Tour:'자동차 투어',
        Tour_Price:'투어 가격',
        People:'인',
        Car:'차',
        Cancellation:'24시간 이내 무료 취소',
        Present_Voucher:'전자 바우처 제시',
        Language_tour:'언어: 투어 프로그램에 따라',
        Pick_Up_Point_Tour:'옵션 호텔 픽업',
        Day_Ticket:'정기권',
        Time:'시간',
        Type_Tour:'투어 종류',
        Number_People:'최소 인원 - 최대',
        People:'인',
        Introduction:'소개',
        Schedule:'일정',
        Include:'포함하다',
        Not_Include:'포함되지',
        Policy:'정책',
        Note:'유의사항',
        Day:'낮',
        Payment_Policy:'지불 정책',
        Cancellation_Policy:'취소 정책',
        Child_Policy:'아동 정책',
        Detail_Tour : '선택한 패키지 세부 정보',
        Tour_Price:'투어 가격',
        Instant_Confirmation:'즉시 확인',
        Confirm:'확인하다',
        Confirm_1:'- 즉시 확인. 주문 확인 이메일을 받지 못한 경우 당사에 문의하십시오.',
        User_Manual:'사용자 매뉴얼',
        Expiry_Date:'만료일',
        Voucher_1 : '- 바우처는 지정된 날짜와 시간에만 유효합니다.',
        Voucher_2 : '- 지정된 날짜와 시간에 바우처를 사용하세요.',
        Hour_Open :'영업시간',
        Week_Time : '- 월요일~일요일: 08:30~18:00',
        Detail_Voucher:'상품권 종류 설명',
        Voucher_3 : '- 출력된 바우처 또는 모바일 바우처 제시',
        View_All:'다 보기',
        Product_Information:'투어 정보',
        Select_Service:'서비스 및 시간을 선택하세요' ,
        Choose_Tour_Date:'날짜',
        Choose_Time:'시간',
        Quantity:'인원',
        Children:'아이',
        Adult:'성인',
        People:'인',
        Time:'시간',
        Departure_Day:'출발일자',
        Return_Day:'도착일자',
        Pick_Up_Time:'픽업 시간',
        Program_Service:'프로그램에 따라 서비스함',
        Type_Of_Room:'객실 종류',
        Tour_Guide:'가이드',
        All_People:'총인원',
        Tax:'세금',
        Tax_Text:'10% 세금 포함',
        Total_Payment:'총 지불금',
        Add_Cart:'자방구니에 넣기',
      },
      hotel:{
        Hotel:'호텔',
        Want_Go:'어디로 떠나세요?',
        Check_In:'체크인',
        Check_Out:'체크아웃',
        Booking_Information:'부킹 정보',
        Adult:'성인',
        Children:'아이',
        Log_In_To_Receive:'호텔 및 항공편 예약 시 15% 쿠폰을 받기 위해 로그인하세요.',
        Number_Of_Room:'객실 수',
        Log_In:'로그인',
        Hotel_Services:'호텔 서비스',
        Filter:'필터',
        All: '모두',
        Start_1:'1성급 호텔',
        Start_2:'2성급 호텔',
        Start_3:'3성급 호텔',
        Start_4:'4성급 호텔',
        Start_5:'5성급 호텔',
        Room_Prices:'객실 가격',
        People:'인',
        // Cancellation:'24시간 이내 무료 취소',
        Present_Voucher:'전자 바우처 제시',
        Language_tour:'언어: 투어 프로그램에 따라',
        Pick_Up_Point_Tour:'옵션 호텔 픽업',
        Day_Ticket:'정기권',
        Time_Check:'체크인 및 체크아웃 시간',
        Address:'주소',
        Number_People:'최소 인원 - 최대',
        Number_People_Text:'각 방의 손님 수에 따라',
        Information:'정보',
        Introduction:'소개',
        Policy:'정책',
        Regulations:'규정',
        Maps:'유지정보',
        Service_Packages:'서비스 패키지',
        Image:'이미지',
        View_room:'객실 정보 보기',
        About_Room:'이 방에 대해',
        Type_Of_Room:'객실 종류',
        Room_Size:'객실 크기',
        Max_Adult:'최대 성인 수',
        Max_Children:'최대 어린이 수',
        Number_Beds:'침대 수',
        Type_Beds:'베드타입',
        Have_Window:'창문이 있습니다',
        Have_Not_Window:'창문 없음',
        Have_Xtra_Bed:'엑스트라 베드 이용 가능',
        Have_Not_Xtra_Bed:'엑스트라 베드 없음',
        Utilities:'유용',
        Beds:'침대',
        Empty_room:'빈방',
        Night:'박',
        Booking:'예약하기',
        Last_Price:'마지막 가격',
        Not_Breakfast :'조식 불포함',
        Cancellation:'정책에 따른 취소',
        Free_Wifi:'무료 와이파이',
        View_Cancellation_Policy:'취소 정책 보기',
        View_Cancellation_Policy_Text_1 : '이 예약을 취소하면 취소 수수료가 무료입니다.',
        View_Cancellation_Policy_Text_2 : '숙박 일수와 객실 유형은 변경할 수 없습니다.',
        View_Cancellation_Policy_Text_3 : '표시된 시간은 현지 시간입니다.',
        Apply_Pay_Check_In : '체크인 시 결제 적용',
        Apply_Pay_Check_In_1 : '체크인 전까지 할인!',
        Apply_Pay_Check_In_Text_1:'체크인 시 결제 적용',
        Apply_Pay_Check_In_Text_2:'추가 여행 유연성: 예약 시 즉시 지불하지 마십시오! 지금 최저가로 예약하고 나중에 체크인 시 현금이나 카드로 결제할 수 있습니다.',
        Extra_Bed_More:'객실 내 엑스트라 베드',
        Company_Fee:'회사 수수료',
        Total_Money:'총금액',

      },
      cart:{
        Cart:'자방구니',
        Golf_Services:'골프 서비스',
        Tour_Services:'투어 서비스',
        Golf_Package_Service :'골프 패키지 서비스',
        Hotel_Services:'호텔 서비스',
        Area:'영역',
        Holes:'홀수',
        P2r1:'2인1실',
        P1r1:'1인 1실',
        Adult:'성인',
        Children:'아이',
        Time:'시간',
        Golf_day:'골프데이',

        Go:'가다',
        Back_Go :'집에가',
        Room : '방',
        Extra_Bed:'추가 침대',
        Check_In_Date_Hotel:'체크인 날짜',
        Check_Out_Date_Hotel:'체크아웃 날짜',
        Number_Of_Room:'방 번호',
        Private_Tour:'개인 투어',
        Compound_Tour:'컴파운드 투어',
        Car_Tour:'자동차 투어',
        Delete:'삭제',
        Total:'총금액',
        Unit:'단위',
        Next:'다음',

      },
      order_summary:{
        Golf_Services:'골프 서비스',
        Tour_Services:'투어 서비스',
        Golf_Package_Service :'골프 패키지 서비스',
        Hotel_Services:'호텔 서비스',
        Select_Order:'주문 선택',
        Check_Information:'정보 확인',
        Pay:'지불하다',
        Area:'영역',
        Holes:'홀수',
        Adult:'성인',
        Children:'아이',
        Time:'시간',
        Golf_day:'골프데이',
        P2r1:'2인1실',
        P1r1:'1인 1실',
        Go:'가다',
        Back_Go :'집에가',
        Room : '방',
        Extra_Bed:'추가 침대',
        Number_Extra_Bed:'엑스트라 베드 수',
        Check_In_Date_Hotel:'체크인 날짜',
        Check_Out_Date_Hotel:'체크아웃 날짜',
        Number_Of_Room:'방 번호',
        Private_Tour:'개인 투어',
        Compound_Tour:'컴파운드 투어',
        Car_Tour:'자동차 투어',
        Buyer_Information:'구매자 정보',
        Full_Name:"이름과 성",
        Account_Name:'계정 이름',
        Email:'이메일',
        Phone:'핸드폰',
        Country:'국가:',
        Edit:'편집하다',
        Communications:'연락',
        Contact_Method:'연락 방법',
        Contact_number:'연락처',
        Pick_Up_Address:'픽업 주소',
        Paying_Address:'수취인 주소',
        Default:'기본',
        Note_Address:'참고: Balotour가 최대한 빨리 픽업 및 하차할 수 있도록 주소를 알려주십시오.',
        Save:'저장',
        Add_Contacts:'연락처 추가',
        Request:'요구',
        Order_Summary:'주문 요약',
        Total:'총금액',
        Include:'포함하다',
        Not_Included:'포함되지',
        Nationality:'국적',
        Delete:'삭제',
        People:'인',
        Type_Tour:'투어 종류',
        Type_Hotel:'호텔 객실 유형',
        Next:'다음',
      },
      payment_method:{
        Select_Order:'주문 선택',
        Check_Information:'정보 확인',
        Pay:'지불하다',
        Payment_methods:'지불 방법',
        Payment_methods_1:'- 현금 또는 일반 이체 방법 이용',
        Payment_methods_2:'- 전자지갑 사용',
        Order_Summary:'주문 요약',
        Total:'총금액',
        Buyer_Information:'구매자 정보',
        Account_Name:'계정 이름',
        Email:'이메일',
        Phone:'핸드폰',
        Nationality:'국적',
        Communications:'연락',
        Contact_Method:'연락 방법',
        Contact_number:'연락처',
        Pick_Up_Address:'픽업 주소',
        Paying_Address:'수취인 주소',
        Request:'요구',
        Pay_Now:'지금 지불하세요',
      },
      order_view:{
        Text_Success:'엄청난! 성공적으로 주문하셨습니다. Balotour를 선택해 주셔서 감사합니다.',
        Order:'주문하다',
        See_Details:'자세히보다',
        Code_Orders:'코드 주문',
        Order_Date:'주문일',
        Payment_Methods:'지불 방법',
        Payment_Status:'지불 상태',
        Transfer:'옮기다',
        Account_Name:'계정 이름',
        Account_No:'계좌 번호',
        At_The_Bank:'은행에서',
        Or:'또는',
        Note:'혜택을 보장하려면 고객이 주의를 기울여야 합니다.',
        Note_1:'정확한 금액을 이체하도록 요청하면 예약이 즉시 확정됩니다.',
        Note_2:'송금 시 결제 내용에 다음 사항을 명시해 주십시오',
        Note_3:'방금 주문한 서비스가 포함된 주문 번호입니다.',
        Note_4:'이 구문을 잘못 입력하면 서비스가 등록 또는 갱신되지 않은 경우에 대해 Balotour는 책임을 지지 않습니다.',
        Text:'Balotour 직원이 가능한 한 빨리 주문을 확인하기 위해 연락을 드릴 것입니다.',
        Text_1:'결제가 완료되고 정보가 정확하고 완전한 경우에만 서비스 등록/갱신이 가능합니다.',
        Text_2:'귀하의 주문이 귀하의 이메일로 전송되었습니다: ',
        Text_3:'. 찾을 수 없으면 스팸 또는 정크 폴더를 확인하십시오.',
        Text_4:'도움이 필요하면 핫라인으로 전화하십시오: (+84) 903001205 또는 0909991205 ',
      },
      contact:{
        Our_Information:'우리의 정보',
        Our_Information_Text:'언제 어디서나 연중무휴 지원',
        Hotline:'핫라인',
        Fanpage:'팬 페이지',
        Email:'이메일',
        Address:'주소',
        Text:'동행할 준비가 되셨습니까?',
        Text_1:'BALOTOUR는 국내외 여행 서비스, 이벤트 조직, 호텔 예약, 골프장, 렌터카, 여행 가이드, 비자 ... 분야에서 명성과 경험을 바탕으로 운영되는 전문 기업입니다. 그리고 외국 기업.',
        Text_2:'확장, 사업 개발 및 강점을 홍보하려는 욕구로 BALOTOUR는 고객 만족을 위해 끊임없이 혁신하고 품질을 향상시킵니다.',
      },
      about:{
        About_Balotour:'Balotour 소개',
        About_Balotour_Text:'Balotour는 국내외 양질의 투어, 이벤트, 골프 투어 및 토너먼트, 팀 빌딩, 자동차 렌탈, 호텔, 빌라, 아파트, 다국어 가이드 및 비자 서비스를 전문으로 합니다.',
        Text:'우리의 임무는 고객이 요청한 투어 프로그램을 올바른 책임을 가진 적임자에게 잘 수행하고 구성하는 것입니다. 발로투어의 엄격한 관리 팀 시스템은 고객님의 여행을 항상 즐겁고 즐겁게 만들어 드리며, 운영자, 운전기사, 가이드까지 열정적이고 세심한 서비스를 제공합니다. 고객이 항상 최고의 경험을 할 수 있도록 행복한 고객이 우리의 성공이라는 모토로.',
        Text_1:'여행 전후의 배려는 고객에게 안전과 만족을 가져다줍니다.',
        Text_2:'새로운 게임으로 투어, 이벤트, 팀 빌딩, 갈라 디너를 구성하세요. 비즈니스 효율성을 높이고 고객의 요구를 충족하며 관광 산업의 새로운 서비스 트렌드를 따라잡습니다. 우리는 베트남 관광 산업이 점점 더 번영하는 데 작은 기여를 할 수 있기를 바랍니다.',
        Text_3:'많은 국내외 기업과 매우 효과적으로 협력하고 있습니다. 확장, 사업 개발 및 우리의 강점을 홍보하려는 열망으로 ',
        Text_4 :' 항상 행복한 여행과 휴가 되시기 바랍니다.',
        Vison_Misson_Titile:'여성 비전 - 사명',
        Vison_Titile:'여성 비전',
        Vison_Titile_Text:'Balotour는 베트남 최고의 10대 여행 서비스 제공업체가 되기 위해 노력하고 있습니다.',
        Misson_Titile:'사명',
        Misson_Titile_Text:'우리는 어디에서나 고객과 함께하고 모두에게 기쁨을 주는 꿈과 소망을 가지고 있습니다. 여행 후 모든 고객이 동지애 및 가족과 유대감을 형성하도록 돕습니다.',
        Core_Values_Title:'핵심 가치',
        Enthusiasm:'열광',
        Enthusiasm_Text:'결단력은 숨결이고, 삶의 목적이며, 자신과 발로투어 팀의 목표입니다. 열정과 열정으로 모든 도전을 이겨내겠습니다.',
        Responsibility:'책임',
        Responsibility_Text:'Balotour는 자신, 고객, 파트너 및 사회에 대한 비즈니스의 약속과 활동으로 정확성과 확실성을 보장하기 위해 끝까지 잘 알고 있으며 책임을 집니다.',
        Creative:'창의적인',
        Creative_Text:'창의성은 영혼이며 생명력입니다. 우리는 진취적인 정신을 유지하며 고객과 파트너에게 탁월한 혜택을 제공하는 솔루션을 끊임없이 찾고 있습니다.',
        Honest:'솔직한',
        Honest_Text:'객관적인 진실을 존중하겠다는 약속. 솔직하고 정직하게 실수로부터 배우십시오.',
        Company_Chart:"회사 차트",
        Partner:'파트너',
        Client:'고객',
      }
    }
    return array
  };
